export const BASE_URL = 'http://13.59.133.37';

export const APPSTATE_LOGGING_IN = 'APPSTATE_LOGGING_IN';
export const LOGINSTATE_LOGGING_IN = 'LOGINSTATE_LOGGING_IN';
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const APPSTATE_SIGNING_UP = 'APPSTATE_SIGNING_UP';
export const LOGINSTATE_LOGGED_IN = 'LOGINSTATE_LOGGED_IN';
export const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER';

export const STUDENT_ROLE = 'Student';
export const COUNSELOR_ROLE = 'Counselor';
