export const BASE_URL = 'http://13.59.133.37';

export const APPSTATE_LOGGING_IN = 'APPSTATE_LOGGING_IN';
export const LOGINSTATE_LOGGING_IN = 'LOGINSTATE_LOGGING_IN';
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const APPSTATE_SIGNING_UP = 'APPSTATE_SIGNING_UP';
export const LOGINSTATE_LOGGED_IN = 'LOGINSTATE_LOGGED_IN';
export const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const APPLY_FILTERS = 'APPLY_FILTERS';
export const DISMISSED_FILTER = 'DISMISSED_FILTER';
export const SET_CHANNEL = 'SET_CHANNEL';
export const SET_MESSAGES = 'SET_MESSAGES';
export const ADD_MESSAGES = 'ADD_MESSAGES';
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const ADD_NOTIFICATIONS = 'ADD_NOTIFICATIONS';
export const REFRESH_PROFILE = 'REFRESH_PROFILE';

export const STUDENT_ROLE = 'Student';
export const COUNSELOR_ROLE = 'Counselor';

export const SENDBIRD_APP_ID = '9F467B70-99DA-4595-A2ED-241BA78C9442';
