export const BASE_URL = 'http://13.59.133.37';

export const APPSTATE_LOGGING_IN = 'APPSTATE_LOGGING_IN';
export const LOGINSTATE_LOGGING_IN = 'LOGINSTATE_LOGGING_IN';
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const APPSTATE_SIGNING_UP = 'APPSTATE_SIGNING_UP';
export const LOGINSTATE_LOGGED_IN = 'LOGINSTATE_LOGGED_IN';
export const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const ADD_CATEGORY_FILTER = 'ADD_CATEGORY_FILTER';
export const REMOVE_CATEGORY_FILTER = 'REMOVE_CATEGORY_FILTER';
export const REMOVE_ALL_FILTERS = 'REMOVE_ALL_FILTERS';
export const ADD_ALL_FILTERS ='ADD_ALL_FILTERS';


export const STUDENT_ROLE = 'Student';
export const COUNSELOR_ROLE = 'Counselor';
