export default {
  LOGO: require('../assets/img/logo.png'),
  LOGO_SMALL: require('../assets/img/logo_small.png'),
  BACK: require('../assets/img/back.png'),
  SEND: require('../assets/img/send.png'),
  NAV_BOT_HIGHLIGHTED: require('../assets/img/nav_bot_blue.png'),
  NAV_BOT: require('../assets/img/nav_bot_grey.png'),
  NAV_FORUM_HIGHLIGHTED: require('../assets/img/nav_forum_blue.png'),
  NAV_FORUM: require('../assets/img/nav_forum_grey.png'),
  NAV_PROFILE_HIGHLIGHTED: require('../assets/img/nav_profile_blue.png'),
  NAV_PROFILE: require('../assets/img/nav_profile_grey.png'),
  UP_ARROW: require('../assets/img/ic_arrow_up.png'),
  HEADER_BG: require('../assets/img/header_bg.png'),
  BOT_USER: require('../assets/img/mini_bot_blue.png'),
  NORMAL_USER: require('../assets/img/user.png'),
};
